config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount Sidekiq::Web => :sidekiq
  devise_for :administrators

  root to: redirect("admin/dashboards/today")

  # authenticated :administrator do
  namespace :admin do
    resources :digital_receipts, only: [:show], param: :uuid
    root to: redirect("admin/dashboards/today")
    resources :administrators
    resources :buildings
    resources :client_displays
    resources :closing_days
    resources :callers, only: [:index]
    resources :companies do
      resources :working_days
      resources :closing_days
    end
    resources :counters
    resources :dashboards do
      get :past, on: :collection
      get :today, on: :collection
      get :future, on: :collection
      get :user_satisfaction_indices, on: :collection
    end
    resources :file_storages
    # resources :permisi_roles
    # resources :permisi_actor_roles
    # resources :permisi_actors
    resources :play_lists
    resources :service_types
    resources :working_days
    resources :services do
      resources :working_days
      resources :closing_days
    end
    resources :shared_clientdisplays
    resources :satisfaction_indices
    resources :user_counters
    resources :user_satisfaction_indices, only: [:index, :show]
    resources :users
    resources :voiceover_buildings
    resources :voice_overs

    resources :digital_receipts, only: [:index]
  end

  namespace :api, defaults: {format: :json} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: 1) do
      devise_for :users
      resources :client_configs, only: [:show]
      resources :callers, only: [:create]
    end
  end
end

app/controllers/api/v1/base_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class BaseController < ApplicationController
      include ApplicationHelper

      include JSONAPI::Pagination
      include JSONAPI::Filtering
      include JSONAPI::Fetching
      include JSONAPI::Deserialization
      include JSONAPI::Errors

      DEFAULT_PAGE_SIZE = 10
      MAX_PAGE_SIZE = 30
      ALLOWED_INCLUDE_LIST = [].freeze

      skip_before_action :verify_authenticity_token

      after_action -> { request.session_options[:skip] = true }

      rescue_from ActiveRecord::RecordNotFound, with: :not_found

      private

      def not_found
        render(
          json: api_error_response("404", "Not found", "Not found", :not_found),
          status: :not_found
        )
      end

      def include_params
        params[:include].present? ? params[:include] : ""
      end

      def allowed_include
        arr = include_params.split(",")
        arr.select { |a| a.in? self.class::ALLOWED_INCLUDE_LIST }
      end

      def jsonapi_serializer_params
        return {} if allowed_include.blank?

        {includes: allowed_include}
      end

      def jsonapi_include
        super & self.class::ALLOWED_INCLUDE_LIST
      end

      def jsonapi_meta(resources)
        pagination = jsonapi_pagination_meta(resources)

        return unless pagination.present?

        {
          pagination: pagination,
          current_page_size: @per_page,
          max_page_size: MAX_PAGE_SIZE
        }
      end

      def jsonapi_page_size(_pagination_params)
        @per_page = params[:size].present? ? params[:size].to_i : DEFAULT_PAGE_SIZE
        @per_page = MAX_PAGE_SIZE if @per_page > MAX_PAGE_SIZE
        @per_page
      end

      def render_jsonapi_internal_server_error(exception)
        raise exception if Rails.env.development?

        Sentry.capture_exception(exception)
        super(exception)
      end
    end
  end
end

app/views/base/_control_sidebar.html.erb
  <!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
  <!-- Control sidebar content goes here -->
  <div class="p-3">
    <h5>Title</h5>
    <p>Sidebar content</p>
  </div>
</aside>
<!-- /.control-sidebar -->

app/views/base/_footer.html.erb
 <!-- Main Footer -->
<footer class="main-footer">
  <!-- To the right -->
  <div class="float-right d-none d-sm-inline">
    QUEUE SYSTEM V3
  </div>
  <!-- Default to the left -->
  <strong>Copyright &copy; <%=Date.current.year%> <a href="https://goo.gl/maps/kND26Sagi9fgBjAcA">ITLIFE Corp</a>.</strong> All rights reserved.
</footer>

app/views/base/_header.html.erb
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
  <!-- Left navbar links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" data-widget="pushmenu" href="#" role="button" id="burger"><i class="fas fa-bars"></i></a>
    </li>
    <%# <li class="nav-item d-none d-sm-inline-block"> %>
    <%# <a href="index3.html" class="nav-link">Home</a> %>
    <%# </li> %>
    <%# <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Contact</a>
      </li> %>
  </ul>
  <!-- Right navbar links -->
  <%# <ul class="navbar-nav ml-auto"> %>
  <!-- Navbar Search -->
  <%# <li class="nav-item"> %>
  <%#=render "base/header/search"%>
  <%# </li> %>
  <!-- Messages Dropdown Menu -->
  <%# <li class="nav-item dropdown"> %>
  <%#=render "base/header/message"%>
  <%# </li> %>
  <!-- Notifications Dropdown Menu -->
  <%# <li class="nav-item dropdown"> %>
  <%#=render "base/header/notification"%>
  <%# </li> %>
  <%# <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
          <i class="fas fa-th-large"></i>
        </a>
      </li> %>
  <%# </ul> %>
</nav>
<!-- /.navbar -->
<script>
  $("#burger").click(function(){
    setTimeout(function(){
      if($("body").attr("class").search("sidebar-collapse") > 0){
        $("#small-logo").removeClass("d-none")
      }else{
        $("#small-logo").addClass("d-none")
      }
    }, 10);
  })
</script>

app/views/base/_sidebar.html.erb
<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <!-- Brand Logo -->
  <%=link_to admin_root_path, class: "brand-link" do%>
    <%=image_tag "small-logo.png", class: "brand-image img-circle elevation-3 d-none", id: "small-logo"%>
    <span class="brand-text"><%=image_tag("logo.png")%></span>
  <% end%>
  <!-- Sidebar -->
  <div class="sidebar">
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
      <div class="image text-white">
        <i class="fa fa-user mt-2"></i>
      </div>
      <div class="info">
        <%=link_to current_administrator.name[0,20] + "..." , root_path %>
      </div>
    </div>
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
      <div class="image text-white">
        <i class="fa fa-building mt-2"></i>
      </div>
      <div class="info">
        <%=link_to current_administrator.company.name[0,20] + "...", root_path %>
      </div>
    </div>
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
      <div class="image">
      </div>
      <div class="info">
        <%=link_to destroy_administrator_session_path, method: :delete, class: "font-weight-bold text-danger" do%>
          Logout <i class="fa fa-sign-out ml-1" aria-hidden="true"></i>
        <%end%>
      </div>
    </div>
    <!-- SidebarSearch Form -->
    <%#=render "base/sidebar/search"%>
    <!-- Sidebar Menu -->
    <nav class="mt-2" style="margin-bottom: 40%">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <%=render "base/sidebar/single_menu", path: admin_callers_path, name: t("callers"), icon: "fa-volume-high"%>
        <%=render "base/sidebar/single_menu", path: admin_companies_path, name: t("company"), icon: "fa-building"%>
        <%=render "base/sidebar/nested_menu", parent: {name: t("dashboard"), icon: "fa-dashboard"}, 
          child: [
            {name: t("past_queue"), path: past_admin_dashboards_path},
            {name: t("today_queue"), path: today_admin_dashboards_path},            
            {name: t("future_queue"), path: future_admin_dashboards_path},
            {name: t("user_satisfaction_index"), path: user_satisfaction_indices_admin_dashboards_path},
          ]%>
        <%=render "base/sidebar/single_menu", path: admin_file_storages_path, name: t("file_storage"), icon: "fa-boxes-packing"%>
        <%=render "base/sidebar/single_menu", path: admin_buildings_path, name: t("building"), icon: "fa-building"%>
        <%=render "base/sidebar/nested_menu", parent: {name: t("setting")}, 
          child: [
            {name: t("client_display"), path: admin_client_displays_path},
            {name: t("service_clientdisplay"), path: admin_shared_clientdisplays_path},
            {name: t("voiceover_buildings"), path: admin_voiceover_buildings_path},            
          ]%>
        <%=render "base/sidebar/single_menu", path: admin_satisfaction_indices_path, name: t("satisfaction_index"), icon: "fa-face-smile"%>
        <%=render "base/sidebar/single_menu", path: admin_user_satisfaction_indices_path, name: t("user_satisfaction_index"), icon: "fa-face-smile-wink"%>
        <%=render "base/sidebar/nested_menu", parent: {name: t("schedule"), icon: "fa-clock"}, 
          child: [            
            {name: t("working_days"), path: admin_working_days_path},
            {name: t("closing_days"), path: admin_closing_days_path},            
          ]%>
        <%=render "base/sidebar/single_menu", path: admin_services_path, name: t("service"), icon: "fa-hand-holding-heart"%>
        <%=render "base/sidebar/nested_menu", parent: {name: t("counter"), icon: "fa-handshake-angle"}, 
          child: [
            {name: t("list"), path: admin_counters_path},
            {name: t("user_counter"), path: admin_user_counters_path}            
          ]%>
        <%=render "base/sidebar/single_menu", path: admin_users_path, name: t("user"), icon: "fa-users"%>
        <%=render "base/sidebar/single_menu", path: admin_voice_overs_path, name: t("voice_over"), icon: "fa-user-astronaut"%>
        <%=render "base/sidebar/single_menu", path: admin_play_lists_path, name: t("play_list"), icon: "fa-music"%>
        <%=render "base/sidebar/single_menu", path: admin_service_types_path, name: t("service_type"), icon: "fa-landmark"%>
      </ul>
    </nav>
    <!-- /.sidebar-menu -->
  </div>
  <!-- /.sidebar -->
</aside>